CREATE PROCEDURE GI_SP_ObterAnuncio
 @CODANUNC varchar(10)
AS
BEGIN
 SELECT 
     CODANUNC
	,ENDANUNC
	,TIPOIMOVANUNC  
	,NOMEPROPANUNC 
	,VALORANUNC 
	,VLRIPTUANUNC 
	,NEGANUNC 
	,REGANUNC 
	,DORMANUNC  
	,SUITEANUNC  
	,VAGASANUNC 
	,AREAANUNC  
	,CIDADEANUNC
	,BAIRROANUNC 
	,OBSANUNC
	,PERMUTAANUNC  
	,CHURRASQUEIRANUNC
	,PISCINAANUNC  
	,BRINQUEDOTECAANUNC
	,PLAYGROUDANUNC 
	,QUADRAANUNC 
	,SGINASTICAANUNC
	,SFESTAANUNC 
	,SJOGOSNUNC  
	,ATIVOANUNC 
 FROM CANUNCIOS
 WHERE CODANUNC = @CODANUNC
END
GO