CREATE PROCEDURE [dbo].[GI_SP_AlterarAnuncio]

     @CODANUNC varchar(6)  
	,@ENDANUNC varchar(160) 
	,@TIPOIMOVANUNC varchar(60) 
	,@NOMEPROPANUNC varchar(100) 
	,@VALORANUNC decimal(18) 
	,@VLRIPTUANUNC decimal(18) 
	,@NEGANUNC varchar(60) 
	,@REGANUNC varchar(60) 
	,@DORMANUNC int 
	,@SUITEANUNC int 
	,@VAGASANUNC int 
	,@AREAANUNC int 
	,@CIDADEANUNC varchar(60) 
	,@BAIRROANUNC varchar(60) 
	,@OBSANUNC varchar(180) 
	,@PERMUTAANUNC bit 
	,@CHURRASQUEIRAANUNC bit 
	,@PISCINAANUNC bit 
	,@BRINQUEDOTECAANUNC bit 
	,@PLAYGROUDANUNC bit 
	,@QUADRAANUNC bit 
	,@SGINASTICAANUNC bit 
	,@SFESTAANUNC bit 
	,@SJOGOSNUNC bit 
	,@ATIVOANUNC char(1) 
	,@DTULTALTANUNC datetime

AS

UPDATE CANUNCIOS
SET

 CODANUNC         =  @CODANUNC         
,ENDANUNC		  =  @ENDANUNC		  
,TIPOIMOVANUNC    =  @TIPOIMOVANUNC    
,NOMEPROPANUNC 	  =  @NOMEPROPANUNC 	  
,VALORANUNC 	  =  @VALORANUNC 	  
,VLRIPTUANUNC 	  =  @VLRIPTUANUNC 	  
,DTULTALTANUNC    =  @DTULTALTANUNC  	  
,NEGANUNC 		  =  @NEGANUNC 		  
,REGANUNC 		  =  @REGANUNC 		  
,DORMANUNC  	  =  @DORMANUNC  	  
,SUITEANUNC  	  =  @SUITEANUNC  	  
,VAGASANUNC 	  =  @VAGASANUNC 	  
,AREAANUNC  	  =  @AREAANUNC  	  
,CIDADEANUNC	  =  @CIDADEANUNC	  
,BAIRROANUNC 	  =  @BAIRROANUNC 	  
,OBSANUNC		  =  @OBSANUNC		  
,PERMUTAANUNC  	  =  @PERMUTAANUNC  	  
,CHURRASQUEIRAANUNC = @CHURRASQUEIRAANUNC 
,PISCINAANUNC  	  =  @PISCINAANUNC  	  
,BRINQUEDOTECAANUNC = @BRINQUEDOTECAANUNC
,PLAYGROUDANUNC   =  @PLAYGROUDANUNC   
,QUADRAANUNC 	  =  @QUADRAANUNC 	  
,SGINASTICAANUNC  =  @SGINASTICAANUNC  
,SFESTAANUNC 	  =  @SFESTAANUNC 	  
,SJOGOSNUNC  	  =  @SJOGOSNUNC  	  
,ATIVOANUNC 	  =  @ATIVOANUNC 	  

