CREATE PROCEDURE [dbo].[GI_SP_AlteraContratos]

 @CODCONTR varchar(10)
,@SITCONTR varchar(3)
,@TIPOIMOVCONTR varchar(60)
,@NOMELOCASCONTR varchar(60)
,@NOMELOCATCONTR varchar(60)
,@DTENTRADACONTR datetime
,@QTAMESESCONTR int
,@DTSAIDACONTR datetime
,@DIAPAGCONTR int
,@VALORCONTR decimal
,@VLRIPTUCONTR decimal
,@CEPCONTR varchar(8)
,@ENDCONTR varchar(160)
,@NUMIMOVCONTR int
,@BAIRROCONTR varchar(60)
,@CIDADECONTR varchar(60)
,@UFCONTR char(2)
,@COMPLCONTR varchar(60)
,@COMPL2CONTR varchar(60)
,@DTULTALTCONTR datetime

AS
 BEGIN
UPDATE CCONTRATOS
SET
 SITCONTR 		= @SITCONTR 
,TIPOIMOVCONTR 	= @TIPOIMOVCONTR 
,NOMELOCASCONTR = @NOMELOCASCONTR
,NOMELOCATCONTR = @NOMELOCATCONTR
,DTENTRADACONTR = @DTENTRADACONTR
,QTAMESESCONTR 	= @QTAMESESCONTR 
,DTSAIDACONTR 	= @DTSAIDACONTR 
,DIAPAGCONTR 	= @DIAPAGCONTR 
,VALORCONTR 	= @VALORCONTR 
,VLRIPTUCONTR 	= @VLRIPTUCONTR 
,CEPCONTR 		= @CEPCONTR 
,ENDCONTR 		= @ENDCONTR 
,NUMIMOVCONTR 	= @NUMIMOVCONTR 
,BAIRROCONTR 	= @BAIRROCONTR 
,CIDADECONTR 	= @CIDADECONTR 
,UFCONTR 		= @UFCONTR 
,COMPLCONTR 	= @COMPLCONTR 
,COMPL2CONTR 	= @COMPL2CONTR 
,DTULTALTCONTR  = @DTULTALTCONTR
 WHERE CODCONTR = @CODCONTR
 END
GO
