CREATE PROCEDURE GI_SP_AltParametros

 @TPSIST  VARCHAR(2)
,@TPCATEG VARCHAR(60)
,@TPPARAM  VARCHAR(10)
,@TPCONTEUDO VARCHAR(MAX)
,@TPDESC VARCHAR(200)
,@TPDTALT DATETIME
,@TPUSU VARCHAR(60)

AS

BEGIN
UPDATE TPARAM 
SET
 TPSIST     =    @TPSIST  
,TPCATEG 	=	@TPCATEG 
,TPCONTEUDO =	@TPCONTEUDO
,TPDESC 	=	@TPDESC 
,TPDTALT 	=	@TPDTALT 
,TPUSU 		=	@TPUSU 
WHERE TPPARAM = @TPPARAM

END
GO