
CREATE PROCEDURE GI_SP_RelListaAnuncio

@FILTRO VARCHAR(100),
@VALOR  VARCHAR(100)

AS

IF(@FILTRO = 'Codigo')
BEGIN
 SELECT 
   CODANUNC
      ,ENDANUNC
      ,TIPOIMOVANUNC
      ,NOMEPROPANUNC
      ,VALORANUNC
      ,VLRIPTUANUNC
      ,DTCADANUNC
      ,DTULTALTANUNC
      ,NEGANUNC
      ,REGANUNC
      ,DORMANUNC
      ,SUITEANUNC
      ,VAGASANUNC
      ,AREAANUNC
      ,CIDADEANUNC
      ,BAIRROANUNC
      ,OBSANUNC
      ,PERMUTAANUNC
      ,CHURRASQUEIRANUNC  
      ,PISCINAANUNC
      ,BRINQUEDOTECAANUNCNC
      ,PLAYGROUDANUNC
      ,QUADRAANUNC
      ,SGINASTICAANUNC
      ,SFESTAANUNC
      ,SJOGOSNUNC
      ,CASE ATIVOANUNC WHEN 'A' THEN 'ATIVO'
	  WHEN 'I' THEN 'INATIVO' END as ATIVOANUNC
 FROM CANUNCIOS
 WHERE CODANUNC = @VALOR
END
ELSE IF(@FILTRO = 'Região')
BEGIN
 SELECT 
  CODANUNC
      ,ENDANUNC
      ,TIPOIMOVANUNC
      ,NOMEPROPANUNC
      ,VALORANUNC
      ,VLRIPTUANUNC
      ,DTCADANUNC
      ,DTULTALTANUNC
      ,NEGANUNC
      ,REGANUNC
      ,DORMANUNC
      ,SUITEANUNC
      ,VAGASANUNC
      ,AREAANUNC
      ,CIDADEANUNC
      ,BAIRROANUNC
      ,OBSANUNC
      ,PERMUTAANUNC
      ,CHURRASQUEIRANUNC  
      ,PISCINAANUNC
      ,BRINQUEDOTECAANUNC
      ,PLAYGROUDANUNC
      ,QUADRAANUNC
      ,SGINASTICAANUNC
      ,SFESTAANUNC
      ,SJOGOSNUNC
      ,CASE ATIVOANUNC WHEN 'A' THEN 'ATIVO'
	  WHEN 'I' THEN 'INATIVO' END as ATIVOANUNC
 FROM CANUNCIOS
 WHERE REGANUNC = @VALOR
 END
 ELSE IF(@FILTRO = 'Proprietario')
BEGIN
 SELECT 
   CODANUNC
      ,ENDANUNC
      ,TIPOIMOVANUNC
      ,NOMEPROPANUNC
      ,VALORANUNC
      ,VLRIPTUANUNC
      ,DTCADANUNC
      ,DTULTALTANUNC
      ,NEGANUNC
      ,REGANUNC
      ,DORMANUNC
      ,SUITEANUNC
      ,VAGASANUNC
      ,AREAANUNC
      ,CIDADEANUNC
      ,BAIRROANUNC
      ,OBSANUNC
      ,PERMUTAANUNC
      ,CHURRASQUEIRANUNC  
      ,PISCINAANUNC
      ,BRINQUEDOTECAANUNC
      ,PLAYGROUDANUNC
      ,QUADRAANUNC
      ,SGINASTICAANUNC
      ,SFESTAANUNC
      ,SJOGOSNUNC
      ,CASE ATIVOANUNC WHEN 'A' THEN 'ATIVO'
	  WHEN 'I' THEN 'INATIVO' END as ATIVOANUNC
 FROM CANUNCIOS
 WHERE NOMEPROPANUNC = @VALOR
 END
  ELSE IF(@FILTRO = 'Tipo de imovel')
BEGIN
 SELECT 
     CODANUNC
      ,ENDANUNC
      ,TIPOIMOVANUNC
      ,NOMEPROPANUNC
      ,VALORANUNC
      ,VLRIPTUANUNC
      ,DTCADANUNC
      ,DTULTALTANUNC
      ,NEGANUNC
      ,REGANUNC
      ,DORMANUNC
      ,SUITEANUNC
      ,VAGASANUNC
      ,AREAANUNC
      ,CIDADEANUNC
      ,BAIRROANUNC
      ,OBSANUNC
      ,PERMUTAANUNC
      ,CHURRASQUEIRANUNC  
      ,PISCINAANUNC
      ,BRINQUEDOTECAANUNC
      ,PLAYGROUDANUNC
      ,QUADRAANUNC
      ,SGINASTICAANUNC
      ,SFESTAANUNC
      ,SJOGOSNUNC
      ,CASE ATIVOANUNC WHEN 'A' THEN 'ATIVO'
	  WHEN 'I' THEN 'INATIVO' END as ATIVOANUNC
 FROM CANUNCIOS
 WHERE TIPOIMOVANUNC = @VALOR
 END
 ELSE
BEGIN
 SELECT 
    CODANUNC
      ,ENDANUNC
      ,TIPOIMOVANUNC
      ,NOMEPROPANUNC
      ,VALORANUNC
      ,VLRIPTUANUNC
      ,DTCADANUNC
      ,DTULTALTANUNC
      ,NEGANUNC
      ,REGANUNC
      ,DORMANUNC
      ,SUITEANUNC
      ,VAGASANUNC
      ,AREAANUNC
      ,CIDADEANUNC
      ,BAIRROANUNC
      ,OBSANUNC
      ,PERMUTAANUNC
      ,CHURRASQUEIRANUNC  
      ,PISCINAANUNC
      ,BRINQUEDOTECAANUNC
      ,PLAYGROUDANUNC
      ,QUADRAANUNC
      ,SGINASTICAANUNC
      ,SFESTAANUNC
      ,SJOGOSNUNC
      ,CASE ATIVOANUNC WHEN 'A' THEN 'ATIVO'
	  WHEN 'I' THEN 'INATIVO' END as ATIVOANUNC
 FROM CANUNCIOS
 END
GO



