CREATE PROCEDURE GI_SP_ObterBoletoRel

@CODCONTR VARCHAR(10),
@CODBOL VARCHAR(10),
@NUMBOL VARCHAR(3)

AS
BEGIN
 SELECT 
 CODBOL   
,CODCONTRBOL 
,NUMBOL 
,ENDERBOL 
,NOMELOCADBOL 
,NOMELOCATBOL
,JRMULBOL  
,VLRBOL  
,VLRMULBOL 
,DTCADBOL  
,DTVCTBOL  
,VLRDESCONTBOL
,DESCONJRBOL  
,VLRIPTUBOL 
,JRCOMBOL  
,VLRCOMBOL 
,PAGBOL 
,DTINIBOL  
,DTFIMBOL 
,CC.TIPOIMOVCONTR
 FROM CBOLETOS
 INNER JOIN CCONTRATOS CC ON CC.CODCONTR = CODCONTRBOL
 WHERE CODCONTRBOL = @CODCONTR AND CODBOL= @CODBOL AND  NUMBOL = @NUMBOL
END
GO

