CREATE PROCEDURE [dbo].[GI_SP_AlterarBoletos]

 @CODBOL varchar(6)  
,@CODCONTRBOL varchar(10)  
,@NUMBOL varchar(3)  
,@ENDERBOL varchar(160) 
,@NOMELOCADBOL varchar(60) 
,@NOMELOCATBOL varchar(60) 
,@JRMULBOL float 
,@VLRBOL decimal 
,@VLRMULBOL decimal
,@DTVCTBOL date 
,@VLRDESCONTBO decimal(18) 
,@DESCONJRBOL float 
,@VLRIPTUBOL decimal(18) 
,@JRCOMBOL float 
,@VLRCOMBOL decimal(18) 
,@PAGBOL char(1) 
,@DTINIBOL date 
,@DTFIMBOL date 
,@DTULTALTBOL datetime 
,@DTPAGBOL datetime

AS

UPDATE CBOLETOS
SET
 CODBOL      = @CODBOL   
,CODCONTRBOL = @CODCONTRBOL  
,NUMBOL 	 = @NUMBOL 
,ENDERBOL 	 = @ENDERBOL 
,NOMELOCADBOL= @NOMELOCADBOL 
,NOMELOCATBOL= @NOMELOCATBOL
,JRMULBOL  	 = @JRMULBOL  
,VLRBOL  	 = @VLRBOL  
,VLRMULBOL 	 = @VLRMULBOL 
,DTVCTBOL  	 = @DTVCTBOL  
,VLRDESCONTBO= @VLRDESCONTBO 
,DESCONJRBOL = @DESCONJRBOL  
,VLRIPTUBOL  = @VLRIPTUBOL 
,JRCOMBOL  	 = @JRCOMBOL  
,VLRCOMBOL 	 = @VLRCOMBOL 
,PAGBOL 	 = @PAGBOL 
,DTINIBOL  	 = @DTINIBOL  
,DTFIMBOL 	 = @DTFIMBOL 
,DTULTALTBOL = @DTULTALTBOL
,DTPAGBOL    = @DTPAGBOL