CREATE PROCEDURE GI_SP_ValidaBoletoPago
 @CODBOL varchar(6)  
,@CODCONTRBOL varchar(10)  
,@NUMBOL varchar(3)  

AS
BEGIN
 SELECT 
 *
 FROM CBOLETOS
 WHERE  CODBOL = @CODBOL AND CODCONTRBOL = @CODCONTRBOL  AND NUMBOL = @NUMBOL AND PAGBOL = 'P'
END