CREATE PROCEDURE [dbo].[GI_SP_PagarBoletos]

 @CODBOL varchar(6)  
,@CODCONTRBOL varchar(10)  
,@NUMBOL varchar(3)  
,@DTPAGBOL datetime

AS

UPDATE CBOLETOS
SET
 DTPAGBOL    = @DTPAGBOL
,PAGBOL      = 'P'
WHERE  CODBOL = @CODBOL AND CODCONTRBOL = @CODCONTRBOL  AND NUMBOL = @NUMBOL 