CREATE PROCEDURE [dbo].[GI_SP_AlteraCliente]

@CODCLI VARCHAR(14)  ,
@CPFCLI VARCHAR(14) ,
@NOMECLI VARCHAR(60) ,
@TELEFCLI VARCHAR(11) ,
@CELCLI VARCHAR(12) ,
@EMAILCLI VARCHAR(60) ,
@TIPOCLI VARCHAR(30) ,
@ATIVOCLI CHAR(1) ,
@CEPCLI VARCHAR(8) ,
@ENDCLI VARCHAR(160) ,
@NUMIMOVCLI INT ,
@BAIRROCLI VARCHAR(60) ,
@CIDADECLI VARCHAR(60) ,
@UFCLI CHAR(1) ,
@COMPLCLI VARCHAR(60) ,
@COMPL2CLI VARCHAR(60),
@DTULTALTCLI DATETIME

AS
 BEGIN
UPDATE CCLIENTES
SET
 CPFCLI = @CPFCLI 
,NOMECLI = @NOMECLI 
,TELEFCLI 	= @TELEFCLI 
,CELCLI 	= @CELCLI 
,EMAILCLI 	= @EMAILCLI 
,TIPOCLI 	= @TIPOCLI 
,ATIVOCLI 	= @ATIVOCLI 
,CEPCLI 	= @CEPCLI 
,ENDCLI 	= @ENDCLI 
,NUMIMOVCLI = @NUMIMOVCLI
,BAIRROCLI 	= @BAIRROCLI 
,CIDADECLI 	= @CIDADECLI 
,UFCLI 		= @UFCLI 
,COMPLCLI 	= @COMPLCLI 
,COMPL2CLI	= @COMPL2CLI
 WHERE CODCLI = @CODCLI
 END
GO
